chunks:
  delay-chunk-unloads-by: 3s
  max-auto-save-chunks-per-tick: 6
  prevent-moving-into-unloaded-chunks: true
collisions:
  max-entity-collisions: 2
entities:
  armor-stands:
    do-collision-entity-lookups: false
    tick: false
  spawning:
    alt-item-despawn-rate:
      enabled: true
      items:
        netherrack: 300
    creative-arrow-despawn-rate: '60'
    skeleton-horse-thunder-spawn-chance: 0.01
environment:
  optimize-explosions: true
  treasure-maps:
    enabled: true
    find-already-discovered:
      loot-tables: 'false'
hopper:
  disable-move-event: true
misc:
  redstone-implementation: alternate-current
tick-rates:
  container-update: 3
  grass-spread: 4
  mob-spawner: 2
